---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: karpenter-provisioner
spec:
  labels:
    intent: apps
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: "karpenter.k8s.aws/instance-family"
      operator: In
      values: ["m5", "t3"]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [small, medium, large]
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
    ttlSecondsAfterEmpty: 30
    ttlSecondsUntilExpired: 2592000
  providerRef:
    name: my-provider
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: my-provider
spec:
  subnetSelector:
    kubernetes.io/cluster/cluster-karpenter: owned
  securityGroupSelector:
    kubernetes.io/cluster/cluster-karpenter: owned